### ISSUE TITLE
make test Error

### ISSUE THREAD

**Issue by igorekRnd** [typiconman/Perl-Lingua-CU#5] opened 2016-10-19 08:57 UTC
Do not pass the tests before installing the module.
I run make test command and displays the following error:

```
#   Failed test 'Church Slavonic collation works'
#   at t/Lingua-CU.t line 62.
#     Structures begin differing at:
#          $got->[0] = 'бцⷣе
#     '
#     $expected->[0] = 'а҆
#     '
# Church Slavonic collation works
# Looks like you failed 1 test of 12.

```

I have installed the latest version of the module Unicode :: Collate.

```
$ perl -e 'use Unicode::Collate; $Collator = Unicode::Collate->new(); print $Collator->UCA_Version()."\n"'
> 30

```

As a workaround, I commented out the line 62 in the test file and reduced the number of test cases to 11:
file t/Lingua-CU.t:

```
-use Test::More tests => 12;
+use Test::More tests => 11;
 -is_deeply (\@output, \@words, "Church Slavonic collation works");
+#is_deeply (\@output, \@words, "Church Slavonic collation works");

```

**Comment by typiconman** [comment] 2016-10-19 09:46
Confirmed.
Lingua::CU::Collate needs to be rewritten to automatically build DUCET tailoring at install based on the installed version of Unicode::Collate.

**Comment by typiconman** [comment] 2018-01-10 10:51
I think that this issue is now fixed.

**Comment by pantlmn** [comment] 2019-03-02 08:52
I get similar error:
`#   Failed test 'Church Slavonic collation works'
#   at t/Lingua-CU.t line 62.
#     Structures begin differing at:
#          $got->[0] = 'є҃
#     '
#     $expected->[0] = 'а҆
#     '
# Church Slavonic collation works
# Looks like you failed 1 test of 12.`

**Comment by typiconman** [comment] 2019-03-02 14:28
I cannot reproduce the error.

Which version of Unicode::Collate are you using? E.g.,

`perl -e "use Unicode::Collate; print Unicode::Collate->UCA_Version()"`

**Comment by pantlmn** [comment] 2019-03-03 09:14
Version 36. Maybe I installed it incorrectly, I'll try once again.

**Comment by pantlmn** [comment] 2019-03-03 09:18
I made once again

    perl Makefile.PL
    make
    make test
    make install

No errors now, `All tests successful.`

**Closed** 2019-03-03 09:53 UTC
Labels: bug
